# Generated by Django 4.2 on 2024-04-13 17:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=15, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gare_depart", models.CharField(max_length=255)),
                ("gare_arrivee", models.CharField(max_length=255)),
                ("date_depart", models.DateTimeField()),
                ("date_arrivee", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateTimeField()),
                ("numero_reservation", models.IntegerField()),
                ("numero_voiture", models.IntegerField()),
                ("numero_place", models.IntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.client"
                    ),
                ),
                (
                    "passager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.passager",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.trajet"
                    ),
                ),
            ],
        ),
    ]
