# Generated by Django 4.2 on 2024-04-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=15, region=None
                    ),
                ),
                ("prenom", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Passager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("date_naissance", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_depart", models.DateTimeField()),
                ("date_arrivee", models.DateTimeField()),
                (
                    "gare_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gare_arrivee",
                        to="booking.gare",
                    ),
                ),
                (
                    "gare_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gare_depart",
                        to="booking.gare",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("date_reservation", models.DateTimeField()),
                (
                    "numero_reservation",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("numero_voiture", models.IntegerField()),
                ("numero_place", models.IntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.client"
                    ),
                ),
                (
                    "passager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.passager",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.trajet"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("trajet", "numero_place"), name="unique_place_par_trajet"
            ),
        ),
    ]
