# Generated by Django 4.2 on 2024-04-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="numero_reservation",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
