# Generated by Django 4.2 on 2024-04-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="passager",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="trajet",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Passager",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.AlterField(
            model_name="trajet",
            name="gare_arrivee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gare_arrivee",
                to="booking.gare",
            ),
        ),
        migrations.AlterField(
            model_name="trajet",
            name="gare_depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gare_depart",
                to="booking.gare",
            ),
        ),
    ]
