# Generated by Django 4.2 on 2024-04-14 19:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_gare_remove_reservation_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajet",
            name="date_arrivee",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 4, 14, 21, 50, 8, 134444)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="trajet",
            name="date_depart",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 4, 14, 21, 50, 8, 134444)
                    )
                ]
            ),
        ),
    ]
