# Generated by Django 4.2 on 2024-04-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_passager_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passager",
            old_name="Client",
            new_name="client",
        ),
    ]
