# Generated by Django 4.2 on 2024-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_trajet_date_arrivee_alter_trajet_date_depart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajet",
            name="date_arrivee",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="trajet",
            name="date_depart",
            field=models.DateTimeField(),
        ),
    ]
