# Generated by Django 4.2 on 2024-04-29 13:25

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_rename_client_passager_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="gare",
            name="position",
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name="trajet",
            name="max_passagers",
            field=models.IntegerField(default=10000),
        ),
    ]
