# Generated by Django 4.2 on 2024-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_passager_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="prénom",
            field=models.CharField(default="", max_length=255),
        ),
    ]
