# Generated by Django 4.2 on 2024-05-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_gare_position_trajet_max_passagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Itineraire',
            fields=[
                ('numero_reservation_it', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.client')),
                ('gare_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='booking.gare')),
                ('gare_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origine', to='booking.gare')),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passager')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation_itineraire',
            constraint=models.UniqueConstraint(fields=('numero_reservation_it',), name='unique_numero_itineraire'),
        ),
    ]
