# Generated by Django 4.2 on 2024-04-29 15:08

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_gare_position_trajet_max_passagers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gare",
            name="position",
            field=geoposition.fields.GeopositionField(
                default="48.8566,2.3522", max_length=42, null=True
            ),
        ),
    ]
