# Generated by Django 4.2 on 2024-04-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_client_nom_client_prénom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="prénom",
            field=models.CharField(max_length=255),
        ),
    ]
