# Generated by Django 4.2 on 2024-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_itineraire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_itineraire',
            name='liste_reservation',
            field=models.ManyToManyField(related_name='reservations_itinerary', to='booking.reservation'),
        ),
    ]
