# Generated by Django 4.2 on 2024-05-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_gare_position"),
        ("booking", "0007_reservation_itineraire_liste_reservation"),
    ]

    operations = []
