# Generated by Django 4.2 on 2024-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="id",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="numero_place",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="numero_reservation",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
