# Generated by Django 4.2 on 2024-04-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0009_remove_reservation_id_alter_reservation_numero_place_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="prénom",
            new_name="prenom",
        ),
    ]
